### ISSUE TITLE
Unable to withdraw: Persistent EVM revert

### ISSUE THREAD

**Issue by Nonprofitflight** [beefyfinance/beefy-app#304] opened 2021-04-11 03:55 UTC
I'm ENTIRELY unable to withdraw anything from any vault whatsoever. I've burnt probably 5 BNB in Tx fees "trying again" or "changing RPCS" after prompted when looking for help, but have never once seen a withdraw succeed. Ever. I opened the wallet in alpha wallet via the mobile app, and have since tried recovering the wallet to both metamask and trust wallet, thinking that might help. It didn't. The only thing I haven't tried is the PC software ( as I currently only have a mobile) and I also considered transferring the MooTokens to a new wallet, but was worried about friction that might cause in the back-end. Android 11 on a Pixel 3.  Alpha wallet 3.24.5(147). Metamask 2.0.1(49). Trust wallet 1.28.0

**Comment by wivern-co-uk** [comment] 2021-04-11 07:33
Sounds like a good question for "tech-support" on discord. Have you checked in there? Link in the app's footer. Also consider to share failing transactions so it's easier to investigate.

**Comment by superbeefyboy** [comment] 2021-04-11 19:56
There are 2 cases. Either a transaction failed, and you have a real failed transaction that can be reviewed. Share it on discord, and people will be able to help you. -> https://discord.gg/beefyfinance

If you don't have a failing transaction, and you only get a popup notification from the RPC endpoint, you don't burn BNB.

Feel free to share any of the failing transactions here or in discord, and we can point you where the problem is.

**Comment by Nonprofitflight** [comment] 2021-04-11 20:11
I lost my Tx history after following instructions to delete all wallets, and restore with seed. Also, I have to go back to Kroger to pay my bills, but I'll send more money there, and send more Txs to build up a new history. Im paying gas fees. I've lost well over 20 bucks trying over and over. I'll have more screens to back that up within the day.

**Comment by superbeefyboy** [comment] 2021-04-11 21:06
20 bucks is not 5 bnb. without tx history this is impossible to validate.
just the public address would be enough to check. But you probably also lost it right??

**Comment by Nonprofitflight** [comment] 2021-04-11 23:29
In the interest of transparency, the comment you're referring to was intended to say ".5" BNB. But you're right. It's not.   I do have the address. It's
 0x70559094cC95482B264c90a1D7622547dFbB3A98

I won't be able to actually be active for another couple hours, but at that point, I'll have extra BNB in the wallet, and will provide screens.

**Comment by BeefyPower** [comment] 2021-04-11 23:33
Set your gwei min to 5 instead of 10.
You are low on gas but it should be good to withdraw unless you are manually lowering the max gas.

**Closed** 2021-04-12 20:50 UTC
