### ISSUE TITLE
The default system language overrides the selected language

### ISSUE THREAD

**Issue by tonytangdev** [beefyfinance/beefy-app#78] opened 2021-01-24 14:03 UTC
## Expected Behavior
When landing on the page, the language should be the one selected in the header menu. If the selected language is English, the texts should be in english.

## Current Behavior
My system is in French and when I open up the app, the selected language is English but some texts are in French.

## Possible Solution
1. Get the system language and make it the selected language
2. On landing, the selected language must be English and the texts must be in English

## Steps to Reproduce
1. Open up the app
2. ![beefy finance](https://user-images.githubusercontent.com/59294334/105632735-202d4180-5e55-11eb-9b49-222987334cf7.png)

## Context (Environment)
- windows 10

**Comment by shibacrypt** [comment] 2021-01-29 12:57
I think you have set the language to `fr` before, and therefore the browser cached it. So when you're viewing it another time, the page automatically displays in French. You can try clearing the cache and then refresh the page. You should see English instead of French.

The issue is that language button not showing the correct language based on the previously stored cached. In your case, it should actually be showing `fr` upon loading instead of `en`. 

Will send up a fix. Thanks for the detailed report!

**Comment by shibacrypt** [comment] 2021-02-10 00:43
If this is verified to be fixed, let's close this issue shall we @sirbeefalot ?

**Comment by roman-monk** [comment] 2021-04-19 09:15
should be fixed now

**Closed by roman-monk** 2021-04-19 09:15 UTC
Labels: bug
